include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - always_declare_return_types
    - lines_longer_than_80_chars
    - camel_case_types
    - avoid_empty_else
    - require_trailing_commas
    - unnecessary_parenthesis
    - sort_unnamed_constructors_first
    - sort_constructors_first
    - prefer_is_empty
    - prefer_is_not_empty
    - directives_ordering
    - always_put_required_named_parameters_first

