name: tcc_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.3.2
  go_router: 8.2.0
  get_it: 7.6.4
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.14
  shared_preferences: ^2.3.3
  equatable: ^2.0.5
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml